Fix ghcjs example in try-reflex output
The `try-reflex` script suggests this example:

```
To create a simple web GUI:
$ cat >hello.hs <<EOF
import Reflex.Dom
main = mainWidget $ text "Hello, world!"
EOF
$ ghcjs hello.hs
Then navigate your browser to file:///home/mgomezch/stuff/code/repo/github.com/reflex-frp/reflex-platform/hello.jsexe/index.html
```

However, doing just that yields a compilation error:

```
[nix-shell:~/stuff/code/repo/github.com/reflex-frp/reflex-platform]$ cat >hello.hs <<EOF
> import Reflex.Dom
> main = mainWidget $ text "Hello, world!"
> EOF

[nix-shell:~/stuff/code/repo/github.com/reflex-frp/reflex-platform]$ ghcjs hello.hs
[1 of 1] Compiling Main             ( hello.hs, hello.js_o )

hello.hs:2:26: error:
    • Couldn't match expected type ‘Data.Text.Internal.Text’
                  with actual type ‘[Char]’
    • In the first argument of ‘text’, namely ‘"Hello, world!"’
      In the second argument of ‘($)’, namely ‘text "Hello, world!"’
      In the expression: mainWidget $ text "Hello, world!"
```

This fails due to the missing `OverloadedStrings` exception.  This can be fixed by adding a `LANGUAGE` pragma to the suggested file contents:

```
$ cat >hello.hs <<EOF
{-# LANGUAGE OverloadedStrings #-}
import Reflex.Dom
main = mainWidget $ text \"Hello, world!\"
EOF
```