Fix ghc example in try-reflex output
The `try-reflex` script suggests this example:
```
To run a simple GUI as a native binary:
$ ghc -e 'import Reflex.Dom' -e 'mainWidget $ text "Hello, world!"'
```

However, doing just that yields a compilation error:

```
[nix-shell:~/stuff/code/repo/github.com/reflex-frp/reflex-platform]$ ghc -e 'import Reflex.Dom' -e 'mainWidget $ text "Hello, world!"'

<interactive>:0:19: error:
    • Couldn't match expected type ‘Data.Text.Internal.Text’
                  with actual type ‘[Char]’
    • In the first argument of ‘text’, namely ‘"Hello, world!"’
      In the second argument of ‘($)’, namely ‘text "Hello, world!"’
      In the expression: mainWidget $ text "Hello, world!"
```

This fails due to the missing `OverloadedStrings` extension.  This can be fixed by adding a command line option to the suggested GHC invocation:

```
$ ghc -XOverloadedStrings -e 'import Reflex.Dom' -e 'mainWidget $ text \"Hello, world!\"'
```